# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCwMKQuXnQxiMubZ0A8KyQ1vS4ZV_7Wz
"""

!pip install transformers torch

from transformers import pipeline

classifier = pipeline("text-classification", model="distilbert-base-uncased-finetuned-sst-2-english")

message = "URGENT: Your bank account has been locked. Verify now: http://secure-login.xyz"

result = classifier(message)

print(result)

label = result[0]['label']
score = result[0]['score']

if label == "LABEL_1":
    risk = score
else:
    risk = 1 - score

risk_percent = round(risk * 100)

if risk_percent >= 70:
    category = "HIGH RISK"
elif risk_percent >= 40:
    category = "SUSPICIOUS"
else:
    category = "LIKELY SAFE"

print("Message:", message)
print("Risk Score:", risk_percent, "/ 100")
print("Category:", category)

message = input("Enter an SMS message to analyze: ")

result = classifier(message)

label = result[0]['label']
score = result[0]['score']

if label == "LABEL_1":
    risk = score
else:
    risk = 1 - score

risk_percent = round(risk * 100)

if risk_percent >= 70:
    category = "HIGH RISK 🔴"
elif risk_percent >= 40:
    category = "SUSPICIOUS 🟡"
else:
    category = "LIKELY SAFE 🟢"

print("-----------------------------")
print("Message:", message)
print("Risk Score:", risk_percent, "/ 100")
print("Category:", category)
print("-----------------------------")

