# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCwMKQuXnQxiMubZ0A8KyQ1vS4ZV_7Wz
"""

!pip install transformers torch

from transformers import pipeline

classifier = pipeline("text-classification", model="mrm8488/bert-tiny-finetuned-sms-spam-detection")

message = "URGENT: Your bank account has been locked. Verify now: http://secure-login.xyz"

result = classifier(message)

print(result)

label = result[0]['label']
score = result[0]['score']

if label == "LABEL_1":
    risk = score
else:
    risk = 1 - score

risk_percent = round(risk * 100)

if risk_percent >= 70:
    category = "HIGH RISK"
elif risk_percent >= 40:
    category = "SUSPICIOUS"
else:
    category = "LIKELY SAFE"

print("Message:", message)
print("Risk Score:", risk_percent, "/ 100")
print("Category:", category)

message = input("Enter an SMS message to analyze: ")

result = classifier(message)

label = result[0]['label']
score = result[0]['score']

if label == "LABEL_1":
    risk = score
else:
    risk = 1 - score

risk_percent = round(risk * 100)

if risk_percent >= 70:
    category = "HIGH RISK 🔴"
elif risk_percent >= 40:
    category = "SUSPICIOUS 🟡"
else:
    category = "LIKELY SAFE 🟢"

print("-----------------------------")
print("Message:", message)
print("Risk Score:", risk_percent, "/ 100")
print("Category:", category)
print("-----------------------------")

!pip install huggingface_hub

from huggingface_hub import login

login(token="ENTER KEY HERE")

from transformers import AutoTokenizer, AutoModelForCausalLM
import torch

tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
model = AutoModelForCausalLM.from_pretrained("google/gemma-2-2b-it", torch_dtype=torch.float16)

print("Gemma 2B ready!")

message = input("Enter an SMS message to analyze: ")

# DistilBERT scores it
result = classifier(message)

label = result[0]['label']
score = result[0]['score']

if label == "LABEL_1":
    risk = score
else:
    risk = 1 - score

risk_percent = round(risk * 100)

if risk_percent >= 70:
    category = "HIGH RISK 🔴"
elif risk_percent >= 40:
    category = "SUSPICIOUS 🟡"
else:
    category = "LIKELY SAFE 🟢"

# Getting Gemma's Reply

prompt = f"""<start_of_turn>user
You are a cybersecurity assistant helping everyday people understand if an SMS message is a phishing scam.

An AI model analyzed this SMS message:
"{message}"

It gave a risk score of {risk_percent} out of 100 and categorized it as {category}.

Please explain in simple, clear steps why this message received that score.
Talk about specific parts of the message that are suspicious or safe.
Write it for someone who is not a tech expert.
Use 4 steps maximum.
<end_of_turn>
<start_of_turn>model
"""

inputs = tokenizer(prompt, return_tensors="pt")
outputs = model.generate(**inputs, max_new_tokens=300)
response = tokenizer.decode(outputs[0], skip_special_tokens=True)

# Extract just Gemma's reply
reply = response.split("<start_of_turn>model")[-1].strip()

print("-----------------------------")
print("MESSAGE:", message)
print("RISK SCORE:", risk_percent, "/ 100")
print("CATEGORY:", category)
print("-----------------------------")
print("GEMMA REASONING:")
print(reply)
print("-----------------------------")

