import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

# To use Transformers in an offline or firewalled environment requires the downloaded and cached files ahead of time. 
model_name = "C:\\Users\\ashle\\.cache\\huggingface\\hub\\models--TinyLlama--TinyLlama-1.1B-Chat-v1.0\\snapshots\\fe8a4ea1ffedaf415f4da2f062534de366a451e6"

tokenizer = AutoTokenizer.from_pretrained(model_name, local_files_only=True)
model = AutoModelForCausalLM.from_pretrained(model_name, local_files_only=True, torch_dtype=torch.float16)

# Download tiny llama tokenizer and model from Hugging Face
#tokenizer = AutoTokenizer.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0")
#model = AutoModelForCausalLM.from_pretrained("TinyLlama/TinyLlama-1.1B-Chat-v1.0", torch_dtype=torch.float16)
"""
messages = [
    {"role": "user", "content": "Who are you?"},
]
inputs = tokenizer.apply_chat_template(
	messages,
	add_generation_prompt=True,
	tokenize=True,
	return_dict=True,
	return_tensors="pt",
).to(model.device)

outputs = model.generate(**inputs, max_new_tokens=40)
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))
"""

# Code modified from Rachna branch/Risk Score & LLM test.py
# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fCwMKQuXnQxiMubZ0A8KyQ1vS4ZV_7Wz
"""
# Use pretrained model from hugging face
classifier = pipeline("text-classification", model="mrm8488/bert-tiny-finetuned-sms-spam-detection")

# test smishing message
message = "URGENT: Your bank account has been locked. Verify now: http://secure-login.xyz"

# model classifies smishing message
result = classifier(message)

# Show Risk score and model output
print("bert-tiny-finetuned is ready!")
print(result)

label = result[0]['label']
score = result[0]['score']

# use LABEL_0 for risk score
"""
if label == "LABEL_1":
    risk = score
else:
    risk = 1 - score
"""
risk = score
risk_percent = round(risk * 100)

if risk_percent >= 70:
    category = "HIGH RISK 🔴"
elif risk_percent >= 40:
    category = "SUSPICIOUS 🟡"
else:
    category = "LIKELY SAFE 🟢"

print("-----------------------------")
print("Message:", message)
print("Risk Score:", risk_percent, "/ 100")
print("Category:", category)
print("-----------------------------")

#tokenizer = AutoTokenizer.from_pretrained("google/gemma-2-2b-it")
#model = AutoModelForCausalLM.from_pretrained("google/gemma-2-2b-it", torch_dtype=torch.float16)

print("Tiny llama ready!")

# Getting Reply

prompt = f"""<start_of_turn>user
You are a cybersecurity assistant helping everyday people understand if an SMS message is a phishing scam.

An AI model analyzed this SMS message:
"{message}"

It gave a risk score of {risk_percent} out of 100 and categorized it as {category}.

Please explain in simple, clear steps why this message received that score.
Talk about specific parts of the message that are suspicious or safe.
Write it for someone who is not a tech expert.
Use 4 steps maximum.
<end_of_turn>
<start_of_turn>model
"""

inputs = tokenizer(prompt, return_tensors="pt")

outputs = model.generate(**inputs, max_new_tokens=300)

# Show LLM chain of thought reasoning
#response = tokenizer.decode(outputs[0], skip_special_tokens=True)
#reply = response.split("<start_of_turn>model")[-1].strip()

# Extract just the LLM's reply
print(tokenizer.decode(outputs[0][inputs["input_ids"].shape[-1]:]))
